version: '2'
services:
    admin225-app:
        image: admin225
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://admin225-postgresql:5432/Admin225
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    admin225-postgresql:
        extends:
            file: postgresql.yml
            service: admin225-postgresql
